### PR TITLE
Allowing for more flexible dump_object queries

### PR DESCRIPTION
**Pull request by pykler**
for example using relationships as part of the where clause.

### CODE REVIEW

**Comment by davedash** [comment]
Not sure I like the new syntax.  Closing for now, feel free to update and we can revisit.

**Comment by pykler** [comment]
Well the idea was to be able to pass any django query ... the "new syntax"
is just json version of a django query. don't think it can get simpler than
that with this flexibility

**Comment by davedash** [comment]
Can you keep both?

You should be able to support:

dump pk1 pk2 pk3
and
dump --query="pk__in=[1,2,3]"

maybe employing the mutual-exclusive arg parser?

**Comment by pykler** [comment]
I updated my fork, any idea if I can update this PR or create a new one?

**Comment by davedash** [comment]
Thanks for this!

**Pull request closed without merging**
