### PR TITLE
Support running dump_object multiple times in single execution

### PR DESCRIPTION
**Pull request by KevinGrahamFoster**
In my workflow, I run dump_object many times in a single execution... The gotcha I hit was the seen dict was never getting cleared, meaning that subsequent calls would be missing things that should be exported. This fix addresses that.

### CODE REVIEW

**Comment by KevinGrahamFoster** [comment]
@davedash Any thoughts on this?

**Comment by davedash** [comment]
Looks good, can you fixup the weird whitespace issues?  Otherwise I can take care of it later.

**Comment by KevinGrahamFoster** [comment]
heh... Sorry that was me pep-8ing. I believe that that's the recommended indent using brackets for include.

**Comment by KevinGrahamFoster** [comment]
I'm fine to change it back tho if you'd rather that.

**Comment by davedash** [comment]
Oh nm, no pep8 good.  I was confused by the diff highlighter.

**Comment by KevinGrahamFoster** [comment]
Awesome, thanks!

**Pull request merged**
